#ILEX-22 - Add endpoints for Single Term Component
MetaCell/interlex pull request #26
Opened 2024-06-20 04:23 UTC by jrmartin

Adds endpoints needed on Single Term Component.

- Adds endpoint to retrieve single Term and Overview information.
- Creates predicates from Term information and stores it inside Term object.
- Adds endpoint to retrieve Variants
- Adds endpoint to retrieve Versions
More information about the endpoints created on this PR can be found in the README in [here](https://github.com/MetaCell/interlex/blob/feature/ILEX-22/src/api/README.md).

Behind the scenes, mock data is being used by orval to simulate the endpoints return. This mock data is parsed into objects the frontend can use on the react components.

2024-07-02 14:01 UTC, ddelpiano requested changes

2024-07-02 14:01 UTC, ddelpiano commented on src/components/SingleTermView/OverView/Predicates.jsx
>    const [loading, setLoading] = useState(false)
If we rely on the useEffect to retrieve the data this should be true or the loader will never be triggered.

2024-07-02 14:01 UTC, ddelpiano commented on src/components/SingleTermView/OverView/Predicates.jsx
> +      console.log("Predicates ", parsedData?.results[0]?.predicates)
remove the console log

2024-07-02 14:01 UTC, ddelpiano commented on src/components/SingleTermView/OverView/PredicatesAccordion.jsx
> +  console.log("Predicates ", data);
remove the console log please

2024-07-02 14:01 UTC, ddelpiano commented on src/components/SingleTermView/OverView/RawDataViewer.jsx
> +      getEndpointsIlxGet("base",dataId, dataFormat).then( rawResponse => {
much cleaner, nice

2024-07-02 14:01 UTC, ddelpiano commented on src/components/Header/Search.jsx
> -    setTerms(parsedData);
This is one of the main problem I have regarding this implementation.
Defining the contract interlex.yaml we should get a model for these data structure that should self-validate the response we get from the backend, simply instantiating the data got to create new class instances from the model created from the yaml that will generate the stubs.
If we start to create parser for every data structure this advantage will be lost and we will have to self validate the data ourself, and in that case I would recommend we pass to typescript and we type the results, the variants, the terms etc to whatever Tom is expecting, but again imho it's a waste of time since this should be done at the contract level. Jesus I understand this is not your decision, but if we want this PR merged I will open a card for technical debt to resolve this, otherwise we keep it open until tomorrow, day of the sprint meeting. This same comment applies to all the classes that we not using right now to cast the data results (terms, term, variants, variant, organizations, organization, etc).

2024-07-02 14:02 UTC, ddelpiano commented on src/components/Header/Search.jsx
> -    setTerms(parsedData);
@jrmartin on this last comment, if you prefer we can open a tech debt card and move forward, otherwise we can solve all tomorrow after the meeting with them.
The other points are simple one solvable already.
Thanks!

2024-07-02 16:07 UTC, jrmartin commented on src/components/Header/Search.jsx
> -    setTerms(parsedData);
`Defining the contract interlex.yaml we should get a model for these data structure that should self-validate the response we get from the backend, simply instantiating the data got to create new class instances from the model created from the yaml that will generate the stubs.`

We already talk with client about this, and doesn't seem that we are getting responses that are self validated against the Open API data model schemas. We can expect basic JSON, JSON+LD or RDF formatted triples , but as far as I know the the server responses won't 'be using data model schemas for validation.  We are going to have to do some Response parsing ourselves to get the information we need from it, which is why those parsers classes were introduced. I agree this parsing is not ideal considering we can just get JSON responses from the server that are formatted already, but that's not what we are getting. 

@ddelpiano Maybe it's best to open  a new card for Tech Debt, as you suggested and move forward with this implementation if we get re-affirmation tomorrow we are not getting responses that are validated against a Data Model schema.

2024-07-03 11:47 UTC, ddelpiano commented on src/components/Header/Search.jsx
> -    setTerms(parsedData);
@jrmartin fine, could you sort the changes requested above? Then I will merge this. Thanks!

2024-07-03 19:41 UTC, jrmartin commented on src/components/Header/Search.jsx
> -    setTerms(parsedData);
`we should get a model for these data structure that should self-validate the response we get from the backend, simply instantiating the data got to create new class instances from the model created from the yaml that will generate the stubs.`

@ddelpiano I made a [new commit ](https://github.com/MetaCell/interlex/pull/26/commits/d8b7d90800246a320e654f50718f6a31fb8aab46) implementing the request above. After looking more into orval, the validation it does is limited to validating the syntax of the OpenAPi contract file (json or yaml), but it does not in itself validate the HTTP response that is coming back from the server. For that we need an external library,  [ajv](https://www.npmjs.com/package/ajv) can compare an HTTP Response with the OpenApi Data Model Schemas.

I made an example/poc of how this would work, while retrieving Organizations which is a mock endpoint.

-  Organizations Data Model is on the contract we created, can be found [here](https://github.com/MetaCell/interlex/blob/d8b7d90800246a320e654f50718f6a31fb8aab46/interlex.yaml#L1074), we will use it to compare the HTTP response format vs this Data Model.
-  As we don't have an endpoint for Organizations, we are [mocking it](https://github.com/MetaCell/interlex/blob/d8b7d90800246a320e654f50718f6a31fb8aab46/interlex.yaml#L132) and we are feeding it this [Mock data](https://github.com/MetaCell/interlex/blob/d8b7d90800246a320e654f50718f6a31fb8aab46/mock/data/mockOrganizations.ts).
- To retrieve organizations, we call the [Mock endpoint](https://github.com/MetaCell/interlex/blob/d8b7d90800246a320e654f50718f6a31fb8aab46/src/api/endpoints/index.ts#L13) and then [validate](https://github.com/MetaCell/interlex/blob/d8b7d90800246a320e654f50718f6a31fb8aab46/src/api/openapi-response-validator.js#L34) the HTTP response against the Data Model for Organizations in the schema. Since the Mock Data for Organizations is not yet complete (it's part of another Issue), the validation will fail. If it were to pass the validation, and the server sent a valid array of Organizations as in the Contract data model,[ we cast the data](https://github.com/MetaCell/interlex/blob/d8b7d90800246a320e654f50718f6a31fb8aab46/src/api/endpoints/index.ts#L18) to the Model generated from the yaml OpenAPi contract and can then use it in the frontend.

2024-07-03 23:14 UTC, ddelpiano commented on src/components/Header/Search.jsx
> -    setTerms(parsedData);
@jrmartin that is cool but imho we don't need it, when we create the stubs from the openapi yaml the stubs are generating the model we define in the contract.
If we want to rely on that, the simpler solution we need there is to instantiate the classes we are expecting each endpoint to return, and if that fails then the response is not according to the contract.
An example:
- https://github.com/MetaCell/interlex/blob/feature/ILEX-22/src/model/term.ts , if I was using the endpoint that should return me a single term then I can simply instantiate a term object from this class using the get request response, that should be good enough if the contract has been followed between backend and frontend.
Thanks!

2024-07-04 08:07 UTC, merged