Feature/ilex 75 Auth UI
MetaCell/interlex pull request #60
Opened 2024-08-20 17:08 UTC by vidhya-metacell

<img width="886" alt="Screen Shot 2024-08-20 at 7 07 00 PM" src="https://github.com/user-attachments/assets/fb198ef8-b576-4697-99d2-f78ae77c363b">
<img width="862" alt="Screen Shot 2024-08-20 at 7 06 54 PM" src="https://github.com/user-attachments/assets/9cce6248-9988-4b38-be7b-bad36ef6dd9e">
<img width="855" alt="Screen Shot 2024-08-20 at 7 06 50 PM" src="https://github.com/user-attachments/assets/cf807ed9-b590-425c-8aa7-d1a772dd691f">
<img width="1283" alt="Screen Shot 2024-08-20 at 7 06 43 PM" src="https://github.com/user-attachments/assets/1771df6a-9dae-4226-adf2-69616c32e53e">

2024-08-26 20:01 UTC, jrmartin requested changes
Looks good @vidhya-metacell ! Just needs to fix conflict issues with devel

2024-08-27 10:02 UTC, vidhya-metacell commented
> Looks good @vidhya-metacell ! Just needs to fix conflict issues with devel

@jrmartin I see no conflicts here

2024-08-27 10:57 UTC, jrmartin commented
> > Looks good @vidhya-metacell ! Just needs to fix conflict issues with devel
> 
> @jrmartin I see no conflicts here

My bad, wrong branch https://github.com/MetaCell/interlex/pull/64 @vidhya-metacell

2024-08-27 10:57 UTC, jrmartin approved these changes

2024-08-27 10:59 UTC, merged