Feature/ilex 34 Terms forks UI
MetaCell/interlex pull request #64
Opened 2024-08-26 16:35 UTC by vidhya-metacell

<img width="1410" alt="Screen Shot 2024-08-26 at 6 34 22 PM" src="https://github.com/user-attachments/assets/e6a0a5d4-bd10-4cdf-9c71-0f43e7326bcc">

2024-08-27 19:29 UTC, jrmartin submitted a review, later dismissed
Looks good!

2024-09-02 08:14 UTC, jrmartin requested changes
Hi @vidhya-metacell , this branch has conflicts now due to older PRs getting merged. Nothing you could have done before since PRs were still pending to be merged. Can you please fix conflicts when you get chance?

2024-09-11 17:31 UTC, vidhya-metacell commented
Hey @jrmartin @ddelpiano , resolved the conflcits

2024-09-11 18:28 UTC, jrmartin approved these changes

2024-09-12 09:56 UTC, merged